name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [15, 16]
        
    container:
      image: postgres:${{ matrix.version }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup PGDG
      run: |
        sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -

    - name: Install dependencies
      env:
        DEBIAN_FRONTEND: noninteractiv
      run: |
        apt-get update
        apt-get install -qy make gcc postgresql-server-dev-${{ matrix.version }} postgresql-${{ matrix.version }}

    - run: make
    - run: make install
    - run: make installcheck
